version: '2'
services:
  umrs-client:
    image: dbTools-client:current
    container_name: dbTools-client-container
    restart: always
    ports:
     - 4201:8000
    logging:
      driver: fluentd
      options:
        fluentd-address: "l-fluentd.ci.aws.labshare.org:24224"
        fluentd-async-connect: "true"
        tag: "auth-ci-ui"
        mode: "non-blocking"
        max-buffer-size: "16m"
